### ISSUE TITLE
/etc/hosts using wrong hostname for localhost

### ISSUE THREAD

**Issue by smiths73v3** [zynthian/zynthian-sys#99] opened 2019-05-18 18:07 UTC
/etc/hosts contains:
127.0.1.1   raspberrypi
>\>sudo true 
>sudo: unable to resolve host zynthian

Should contain entry for host name specified in /etc/hostname
>\>cat /etc/hostname
>zynthian

set /etc/hosts to contain entry:
127.0.1.1  zynthian

>\>sed -i.bak -e "s/raspberrypi/\`cat /etc/hostname\`/" /etc/hosts 
>\>sudo true
>\>

**Comment by guysoft** [comment] 2019-05-19 10:44
The hostname is being changed twice in the image build.
From the build.log of last nightly.

Change one form ZynthianOS's configuration:
```
+ cp /CustomPiOS/modules/base/end_chroot_script chroot_script
+ chmod 755 chroot_script
+ cp /CustomPiOS/common.sh common.sh
+ chmod 755 common.sh
+ chroot . usr/bin/qemu-arm-static /bin/bash /chroot_script
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -f /etc/hostname ']'
+ read FILE_HOST_NAME
+ FILE_HOST_NAME=zynthian
+ echo zynthian
+ sed -i -e s@zynthian@zynthian@g /etc/hosts
+ '[' -d custompios_export ']'
+ rm chroot_script
```

Change two from the zynthian-sys repo:

```
export ZYNTHIAN_CHANGE_HOSTNAME=yes
+ ZYNTHIAN_CHANGE_HOSTNAME=yes
```

**Comment by smiths73v3** [comment] 2019-05-19 17:28
hostname entry in /etc/hostname does not appear in /etc/hosts with a 127.0.x.x address, causing hostname lookup failures.

>\>cat /etc/hostname
>zynthian
>\>cat /etc/hosts
>127.0.0.1       localhost
>::1             localhost ip6-localhost ip6-loopback
>ff02::1         ip6-allnodes
>ff02::2         ip6-allrouters
>
>127.0.1.1       raspberrypi

Where the last entry should be "zynthian" not "raspberrypi" or whatever /etc/hostname has been changed to.

In the script above, the sed modify to /etc/hosts appears wrong. I believe it should be:
>\>sed -i -e s@raspberrypi@zynthian@g /etc/hosts

**Comment by jofemodo** [comment] 2019-05-20 18:56
Sorry, i can't reproduce the error.

**Comment by smiths73v3** [comment] 2019-05-25 16:25
Possible fix, small change to setup script. See pull request.

**Comment by jofemodo** [comment] 2019-05-30 10:41
OK! I've merged the pull request. I will change the webconf code accordingly.

**Closed** 2019-05-30 11:44 UTC
Labels: bug

**Comment by smiths73v3** [comment] 2019-06-05 16:44
Verified in my RC2, this is resolved.
