### ISSUE TITLE
MOD-SDK Start Error

### ISSUE THREAD

**Issue by rodamaralgeo** [zynthian/zynthian-sys#90] opened 2019-05-06 20:42 UTC
Version: **Zynthian-OS (2019-05-03)**
When trying to start MOD-SDK the following error is displayed:
![8748d8e7c7543690f70680af0de127cc12026ba8](https://user-images.githubusercontent.com/28227717/57253916-44644180-7026-11e9-8444-2b107f0b31cf.png)
![start_modsdk](https://user-images.githubusercontent.com/28227717/57253917-44644180-7026-11e9-9b8a-f6dab7efbeb7.png)

**Comment by riban-bw** [comment] 2019-05-15 21:40
Is this a requirement for ARUK? I am not aware that MOD-SDK is a core function of Zynthian. Will the failure to run MOD-SDK block roll-out of ARUK?

**Comment by jofemodo** [comment] 2019-05-16 09:02
It's not a core function. MOD-SDK is a Web-GUI that is mainly useful for LV2-plugin developpers. It worked in Gorgona and should work in Aruk, but it's not critical at all. Also, i'm pretty sure that the problem is easy to solve ;-)

**Comment by jofemodo** [comment] 2021-09-21 07:57
Since mod-sdk is not present by default on recent SD images, i will close this.

**Closed by jofemodo** 2021-09-21 07:57 UTC
Labels: bug, ARUK
